#!/bin/sh

# Copyright 2024 Sowers, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

echo "Building Docker Image...."

ROOT=`pwd`

tag="latest"

if [ "$IMAGE_TAG" != "" ]; then
  tag="$IMAGE_TAG"
fi

docker build -t ghcr.io/sowers-io/bosca/text-extractor:latest .
docker image tag ghcr.io/sowers-io/bosca/text-extractor:latest ghcr.io/sowers-io/bosca/text-extractor:$tag

echo "...done"